# Generated by Django 5.0.6 on 2025-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0051_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase del icono de Bootstrap (ej: bi-house-door)', max_length=50, null=True),
        ),
    ]
